# Generated by Django 5.0.7 on 2025-05-09 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('IN', 'Kirim'), ('OUT', 'Chiqim')], max_length=3)),
                ('category', models.CharField(choices=[('oylik', 'Oylik ish haqi'), ('avans', 'Avans'), ('kunlik', 'Kunlik ish'), ('sovga', 'Sovg‘a'), ('xizmat', 'Xizmat haqi'), ('boshqa_kirim', 'Boshqa kirim'), ('ovqat', 'Ovqat'), ('yoqilg‘i', 'Yoqilg‘i'), ('ijara', 'Ijara haqi'), ('internet', 'Internet/xizmatlar'), ('sotib_olish', 'Sotib olish'), ('boshqa_chiqim', 'Boshqa chiqim')], max_length=50)),
                ('pul_turi', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('valyuta', 'Valyuta')], default='naqd', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sana'],
            },
        ),
    ]
