# Generated by Django 5.0.7 on 2025-05-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KirimChiqim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-data']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sana',
            new_name='data',
        ),
    ]
