# Generated by Django 5.0.7 on 2025-05-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KirimChiqim', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='data',
            new_name='date',
        ),
    ]
