# Generated by Django 5.0.7 on 2025-05-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KirimChiqim', '0004_transaction_karta_nomi_transaction_valyuta_turi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
